StartupEvents.registry('block', event => {
    event.create('gobber_glass_dragon')
    .displayName('Dragon Glass')
    .soundType('glass')
    .mapColor('color_magenta')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('c:needs_end_gobber_tool')
    .hardness(0.9)
    .resistance(100.0)
    .lightLevel(1)
    .opaque(false)
    .texture('magical_addons:block/gobber_glass_dragon')
    .noValidSpawns(true)
    .suffocating(false)
    .requiresTool(true)
    .defaultTranslucent()
})