//Particle Blocks
StartupEvents.registry('block', event => {
  event.create('purple_drip_block')
    .displayName('Purple Drip Block')
    .soundType('glass')
    .hardness(0)
    .resistance(0)
    .fullBlock(true)
    .requiresTool(false)
    .opaque(false)
    .renderType('cutout')
    .texture('magical_addons:block/0empty')
    .noCollision()
    .notSolid()
    .noDrops()
    .suffocating(false)
    .viewBlocking(false)
    .redstoneConductor(false)
    .noValidSpawns(true)
    .transparent(true)
    .defaultCutout()
    .randomTick(tick => {
      console.log(tick);
    })

  event.create('purple_star_block')
    .displayName('Purple Star Block')
    .soundType('glass')
    .hardness(0)
    .resistance(0)
    .fullBlock(true)
    .requiresTool(false)
    .opaque(false)
    .renderType('cutout')
    .texture('magical_addons:block/0empty')
    .noCollision()
    .notSolid()
    .noDrops()
    .suffocating(false)
    .viewBlocking(false)
    .redstoneConductor(false)
    .noValidSpawns(true)
    .transparent(true)
    .defaultCutout()
    .randomTick(tick => {
      console.log(tick);
    })

    event.create('spiting_lava_particle_block')
    .displayName('Spiting Lava Block')
    .soundType('glass')
    .hardness(0)
    .resistance(0)
    .fullBlock(true)
    .requiresTool(false)
    .opaque(false)
    .renderType('cutout')
    .texture('magical_addons:block/0empty')
    .noCollision()
    .notSolid()
    .noDrops()
    .suffocating(false)
    .viewBlocking(false)
    .redstoneConductor(false)
    .noValidSpawns(true)
    .transparent(true)
    .defaultCutout()
    .randomTick(tick => {
      console.log(tick);
    })
})