StartupEvents.registry('particle_type', event => {
    event.create('black_shine', 'basic')
    event.create('grey_shine', 'basic')
    event.create('light_grey_shine', 'basic')
    event.create('white_shine', 'basic')
    event.create('brown_shine', 'basic')
    event.create('red_shine', 'basic')
    event.create('orange_shine', 'basic')
    event.create('yellow_shine', 'basic')
    event.create('green_shine', 'basic')
    event.create('lime_shine', 'basic')
    event.create('cyan_shine', 'basic')
    event.create('light_blue_shine', 'basic')
    event.create('blue_shine', 'basic')
    event.create('purple_shine', 'basic')
    event.create('magenta_shine', 'basic')
    event.create('pink_shine', 'basic')
})