//Blocks

StartupEvents.registry('block', event => {
  event.create('powered_silver_block', 'basic')
    .displayName('Powered Silver Block')
    .soundType('metal')
    .hardness(2.5)
    .resistance(3.5)
    .fullBlock(true)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .texture('north', 'magical_addons:block/silver_block_face_1')
    .texture('east', 'magical_addons:block/silver_block_face_2')
    .texture('south', 'magical_addons:block/silver_block_face_3')
    .texture('west', 'magical_addons:block/silver_block_face_4')
    .texture('up', 'magical_addons:block/silver_block_face_5')
    .texture('down', 'magical_addons:block/silver_block_face_6')
})

//Particle Blocks

StartupEvents.registry('block', event => {
  event.create('purple_drip_block', 'basic')
    .displayName('Purple Drip Block')
    .soundType('glass')
    .hardness(0)
    .resistance(0)
    .fullBlock(true)
    .requiresTool(false)
    .opaque(false)
    .renderType('cutout')
    .textureAll('magical_addons:block/the_glass')
    .noCollision()
    .notSolid()
    .noDrops()
    .suffocating(false)
    .viewBlocking(false)
    .redstoneConductor(false)
    .noValidSpawns(false)
    .transparent(true)
    .defaultCutout()
    .randomTick(tick => {
      console.log(tick);
    })

  event.create('purple_star_block', 'basic')
    .displayName('Purple Star Block')
    .soundType('glass')
    .hardness(0)
    .resistance(0)
    .fullBlock(true)
    .requiresTool(false)
    .opaque(false)
    .renderType('cutout')
    .textureAll('magical_addons:block/the_glass')
    .noCollision()
    .notSolid()
    .noDrops()
    .suffocating(false)
    .viewBlocking(false)
    .redstoneConductor(false)
    .noValidSpawns(false)
    .transparent(true)
    .defaultCutout()
    .randomTick(tick => {
      console.log(tick);
    })

    event.create('spiting_lava_particle_block', 'basic')
    .displayName('Spiting Lava Block')
    .soundType('glass')
    .hardness(0)
    .resistance(0)
    .fullBlock(true)
    .requiresTool(false)
    .opaque(false)
    .renderType('cutout')
    .textureAll('magical_addons:block/the_glass')
    .noCollision()
    .notSolid()
    .noDrops()
    .suffocating(false)
    .viewBlocking(false)
    .redstoneConductor(false)
    .noValidSpawns(false)
    .transparent(true)
    .defaultCutout()
    .randomTick(tick => {
      console.log(tick);
    })
})