version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
mcwfences = true
farmersdelight = true
mythicmetals = true
mcwroofs = true
alloy_forgery = true
imbued_deco = true
oxidized = true
mcwwindows = true
storagedrawers = true
betternether = true
mythicmounts = true
festive_delight = true
betterend = true
twigs = true
ecologics = true
libraryferret = true
stonezone = true
gobber2 = true
comforts = true
hexcasting = true
darkutils = true
yigd = true
nethersdelight = true
fastpaintings = true
things = true
mythicmetals_decorations = true
mcwlights = true
mcwtrpdoors = true
amendments = true
handcrafted = true
ftbquests = true
bewitchment = true
amethyst_imbuement = true
morevillagers = true
endersdelight = true
kubejs = true
mcwdoors = true
ironchests = true
nightlights = true
supplementaries = true
botania = true
suppsquared = true
chipped = true
sawmill = true
biomeswevegone = true
minecraft = true
lootr = true
archon = true
regions_unexplored = true
mcwfurnitures = true
betterarcheology = true
bosses_of_mass_destruction = true
waystones = true
decorative_blocks = true
besmirchment = true
crittersandcompanions = true
gofish = true
expandeddelight = true
